//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCRavenSaga.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apoyos
    {
        public int IDApoyo { get; set; }
        public int IDUnitA { get; set; }
        public int IDUnitB { get; set; }
        public int IDElemA { get; set; }
        public int IDElemB { get; set; }
        public bool Romance { get; set; }
    
        public virtual Elementos Elementos { get; set; }
        public virtual Elementos Elementos1 { get; set; }
        public virtual Unidades Unidades { get; set; }
        public virtual Unidades Unidades1 { get; set; }
    }
}
