//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCRavenSaga.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArbolClases
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ArbolClases()
        {
            this.Armas = new HashSet<Armas>();
            this.Unidades = new HashSet<Unidades>();
            this.Unidades1 = new HashSet<Unidades>();
        }
    
        public int IDClase { get; set; }
        public string Clase { get; set; }
        public int HPMax { get; set; }
        public int FuerzaMax { get; set; }
        public int MagiaMax { get; set; }
        public int HabMax { get; set; }
        public int VelMax { get; set; }
        public int SuerMax { get; set; }
        public int DefMax { get; set; }
        public int ResMax { get; set; }
        public bool Promocion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Armas> Armas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Unidades> Unidades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Unidades> Unidades1 { get; set; }
    }
}
