//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCRavenSaga.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Armas
    {
        public int IDObjeto { get; set; }
        public string Nombre { get; set; }
        public int Mt { get; set; }
        public int Hit { get; set; }
        public int Crit { get; set; }
        public int Wt { get; set; }
        public bool ArmaPersonal { get; set; }
        public int IDClase { get; set; }
        public string Imagen { get; set; }
        public string TipoArma { get; set; }
    
        public virtual ArbolClases ArbolClases { get; set; }
    }
}
