//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCRavenSaga.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Unidades
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Unidades()
        {
            this.Apoyos = new HashSet<Apoyos>();
            this.Apoyos1 = new HashSet<Apoyos>();
        }
    
        public int IDUnit { get; set; }
        public string Nombre { get; set; }
        public int Nivel { get; set; }
        public int HP { get; set; }
        public int Fuerza { get; set; }
        public int Magia { get; set; }
        public int Habilidad { get; set; }
        public int Velocidad { get; set; }
        public int Suerte { get; set; }
        public int Defensa { get; set; }
        public int Resistencia { get; set; }
        public int HPGr { get; set; }
        public int FueGr { get; set; }
        public int MagGr { get; set; }
        public int HabGr { get; set; }
        public int VelGr { get; set; }
        public int SuerGr { get; set; }
        public int DefGr { get; set; }
        public int ResGr { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public int IDElemento { get; set; }
        public string Imagen { get; set; }
        public int IDClase { get; set; }
        public int IDPromocion { get; set; }
        public bool Promovido { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Apoyos> Apoyos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Apoyos> Apoyos1 { get; set; }
        public virtual Elementos Elementos { get; set; }
        public virtual ArbolClases ArbolClases { get; set; }
        public virtual ArbolClases ArbolClases1 { get; set; }
    }
}
