//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Apoyos
{
    public int IDApoyo { get; set; }
    public int IDUnitA { get; set; }
    public int IDUnitB { get; set; }
    public int IDElemA { get; set; }
    public int IDElemB { get; set; }
    public bool Romance { get; set; }

    public virtual Elementos Elementos { get; set; }
    public virtual Elementos Elementos1 { get; set; }
    public virtual Unidades Unidades { get; set; }
    public virtual Unidades Unidades1 { get; set; }
}

public partial class ArbolClases
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ArbolClases()
    {
        this.Armas = new HashSet<Armas>();
        this.Unidades = new HashSet<Unidades>();
        this.Unidades1 = new HashSet<Unidades>();
    }

    public int IDClase { get; set; }
    public string Clase { get; set; }
    public int HPMax { get; set; }
    public int FuerzaMax { get; set; }
    public int MagiaMax { get; set; }
    public int HabMax { get; set; }
    public int VelMax { get; set; }
    public int SuerMax { get; set; }
    public int DefMax { get; set; }
    public int ResMax { get; set; }
    public bool Promocion { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Armas> Armas { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Unidades> Unidades { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Unidades> Unidades1 { get; set; }
}

public partial class Armas
{
    public int IDObjeto { get; set; }
    public string TipoArma { get; set; }
    public string Nombre { get; set; }
    public int Mt { get; set; }
    public int Hit { get; set; }
    public int Crit { get; set; }
    public int Wt { get; set; }
    public bool ArmaPersonal { get; set; }
    public int IDClase { get; set; }
    public string Imagen { get; set; }

    public virtual ArbolClases ArbolClases { get; set; }
}

public partial class Elementos
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Elementos()
    {
        this.Apoyos = new HashSet<Apoyos>();
        this.Apoyos1 = new HashSet<Apoyos>();
        this.Unidades = new HashSet<Unidades>();
    }

    public int IDElemento { get; set; }
    public string Elemento { get; set; }
    public string Bonificaciones { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Apoyos> Apoyos { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Apoyos> Apoyos1 { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Unidades> Unidades { get; set; }
}

public partial class Unidades
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Unidades()
    {
        this.Apoyos = new HashSet<Apoyos>();
        this.Apoyos1 = new HashSet<Apoyos>();
    }

    public int IDUnit { get; set; }
    public string Nombre { get; set; }
    public int IDClase { get; set; }
    public int IDPromocion { get; set; }
    public int Nivel { get; set; }
    public int HP { get; set; }
    public int Fuerza { get; set; }
    public int Magia { get; set; }
    public int Habilidad { get; set; }
    public int Velocidad { get; set; }
    public int Suerte { get; set; }
    public int Defensa { get; set; }
    public int Resistencia { get; set; }
    public int HPGr { get; set; }
    public int FueGr { get; set; }
    public int MagGr { get; set; }
    public int HabGr { get; set; }
    public int VelGr { get; set; }
    public int SuerGr { get; set; }
    public int DefGr { get; set; }
    public int ResGr { get; set; }
    public System.DateTime FechaNacimiento { get; set; }
    public int IDElemento { get; set; }
    public string Imagen { get; set; }
    public bool Promovido { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Apoyos> Apoyos { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Apoyos> Apoyos1 { get; set; }
    public virtual ArbolClases ArbolClases { get; set; }
    public virtual ArbolClases ArbolClases1 { get; set; }
    public virtual Elementos Elementos { get; set; }
}
